program: r0123456.py
method: bayes
metric:
  name: best objective
  goal: minimize
parameters:
  k:
    value: 7
  alpha:
    value: 0.1
  alpha_sharing:
    min: 0.1
    max: 3.0
  sigmaPerc:
    min: 0.1
    max: 0.9
  sharedElimDecay_alpha:
    min: 1.0
    max: 3.0
  sharedElimDecay_n:
    min: 10 
    max: 40
  sharedElimDecay_c:
    min: 0.0
    max: 0.3
  LSO_alpha:
    min: 1.0
    max: 3.0
  LSO_n:
    min: 1.0
    max: 5.0
  LSO_c:
    min: 0.0
    max: 0.3
  mutation:
    value: ["inversion"]
  recombination:
    values: ["basic","edge"]
  percent_greedy_init:
    min: 0.01
    max: 0.2
  lambStart:
    min: 20
    max: 150
  lambEnd:
    min: 5
    max: 20
  lambDecay_n:
    min: 0.5
    max: 1.0
  tour:
    value: 750
  
  