program: r0123456.py
method: bayes
metric:
  name: best objective
  goal: minimize
parameters:
  k:
    min: 3
    max: 10
  alpha:
    value: 0.1
  alpha_sharing:
    min: 0.1
    max: 3.0
  sigmaPerc:
    min: 0.1
    max: 0.9
  sharedElimDecay_alpha:
    min: 0.5
    max: 10.0
  sharedElimDecay_n:
    value: 50.0
  sharedElimDecay_c:
    value: 0.0
  LSO_alpha:
    value: 0.0
  LSO_n:
    value: 2.0
  LSO_c:
    min: 0.2
    max: 1.0
  percent_greedy_init:
    min: 0.01
    max: 0.2
  lambStart:
    min: 10
    max: 100
  lambDecay_n:
    value: 1
  tour:
    value: 50
  mutation:
    value: ["inversion"]
  recombination:
    values: ["basic"]

  
  