program: r0123456copy.py
method: random
metric:
  name: best objective
  goal: minimize
parameters:

  k:
    value: 5

  alpha_sharing:
    value: 1.5
  sigmaPerc:
    value: 0.2
  
  sharedElimDecay_alpha:
    value: 1
  sharedElimDecay_n:
    value: 15
  sharedElimDecay_c:
    value: 0

  LSO_alpha:
    value: 5
  LSO_n:
    value: 4
  LSO_c:
    value: 0.2
  LSOPercent:
    value: 0.7

  alpha:
    value: 0.1
  alphaStart:
    value: 0.3
  alphaEnd:
    value: 0.1
  alphaDecay_n:
    value: 0.4

  mutation:
    value: ["inversion"]
  recombination:
    value: ["basic"]
  percent_greedy_init:
    value: 0.2

  lambStart:
    value: 80
  lambEnd:
    value: 40
  lambDecay_n:
    value: 0.8
  tour:
    value: 100
  
  
