program: r0123456.py
method: bayes
metric:
  name: best objective
  goal: minimize
parameters:

  k:
    value: 7
  alpha:
    value: 0.1

  alpha_sharing:
    values: [0.5,1.0,1.5,2.0,2.5,3.0]
  sigmaPerc:
    values: [0.1,0.2,0.3,0.4,0.5]
  
  sharedElimDecay_alpha:
    values: [0.4,0.6,0.8,1.0]
  sharedElimDecay_n:
    value: 50
  sharedElimDecay_c:
    values: [0.0,0.1,0.2,0.3]

  LSO_alpha:
    values: [1,2,3,4,5]
  LSO_n:
    values: [1,2,3,4,5]
  LSO_c:
    values: [0.0,0.1,0.2,0.3]

  mutation:
    value: ["inversion"]
  recombination:
    values: ["basic"]

  percent_greedy_init:
    values: [0.05,0.1,0.15,0.2,0.25,0.3]

  lambStart:
    values: [80,100,120,140,180]
  lambEnd:
    values: [15,30,45]
  lambDecay_n:
    value: [0.6,0.7,0.8,0.9]
  tour:
    value: 200
  
  