program: r0123456.py
method: bayes
metric:
  name: best objective
  goal: minimize
parameters:

  k:
    values: [5,6,7]

  alpha_sharing:
    values: [0.5,1.0,1.5,2.0,2.5,3.0]
  sigmaPerc:
    values: [0.1,0.2,0.3,0.4,0.5]
  
  sharedElimDecay_alpha:
    value: 0.8
  sharedElimDecay_n:
    value: 50
  sharedElimDecay_c:
    value: 0

  LSO_alpha:
    min: 1.0
    max: 10.0
  LSO_n:
    min: 1.0
    max: 20.0
  LSO_c:
    values: [0.0,0.1,0.2,0.3,0.4,0.5]
  LSOPercent:
    values: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95]

  alpha:
    value: 0.1
  alphaStart:
    values: [0.1,0.2,0.3,0.4,0.5]
  alphaEnd:
    value: 0.1
  alphaDecay_n:
    value: 0.4

  mutation:
    value: ["inversion"]
  recombination:
    values: ["basic","edge","order","cycle","scx"]
  percent_greedy_init:
    values: [0.05,0.1,0.15,0.2,0.25,0.3]

  lambStart:
    values: [80,100,120,140,160,180,200,220]
  lambEnd:
    values: [10,20,40,60,80]
  lambDecay_n:
    values: [0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6]
  tour:
    value: 750
  